// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solar.Infrastructure.Context;

#nullable disable

namespace Solar.Infrastructure.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    [Migration("20241114151659_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solar.Domain.Agg.Aggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Earnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyConsumptionTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyDirectConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyOutput")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergyProductionTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EnergySelfConsumptionTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Profits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PvSystemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Savings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsCO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsTravelCar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsTravelPlane")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsTrees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Aggregates");
                });

            modelBuilder.Entity("Solar.Domain.Equipment.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
